/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


 

/**
 *
 * @author kiara.jung
 */
public class NewJFrame extends javax.swing.JFrame {
    


    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameFileChooser = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        TextFeld1 = new javax.swing.JTextField();
        EingabeB = new javax.swing.JButton();
        WahlTuringB = new javax.swing.JButton();
        jTextFieldTuring = new javax.swing.JTextField();
        jLabelWort = new javax.swing.JLabel();
        jLabelTuring = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAusgabe1 = new javax.swing.JTextArea();
        jLabelAusgabe1 = new javax.swing.JLabel();
        jButtonStarten1 = new javax.swing.JButton();

        jFrameFileChooser.setSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout jFrameFileChooserLayout = new javax.swing.GroupLayout(jFrameFileChooser.getContentPane());
        jFrameFileChooser.getContentPane().setLayout(jFrameFileChooserLayout);
        jFrameFileChooserLayout.setHorizontalGroup(
            jFrameFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameFileChooserLayout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrameFileChooserLayout.setVerticalGroup(
            jFrameFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameFileChooserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFileChooser1.getAccessibleContext().setAccessibleParent(WahlTuringB);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EingabeB.setText("Wort einlesen");
        EingabeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EingabeBActionPerformed(evt);
            }
        });

        WahlTuringB.setText("Wähle Turing-Maschine");
        WahlTuringB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WahlTuringBActionPerformed(evt);
            }
        });

        jTextFieldTuring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTuringActionPerformed(evt);
            }
        });

        jLabelWort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelWort.setText("Das einzulesende Wort eintragen:");

        jLabelTuring.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTuring.setText("Folgende Datei gewählt:");

        jTextAreaAusgabe1.setColumns(20);
        jTextAreaAusgabe1.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAusgabe1);

        jLabelAusgabe1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAusgabe1.setText("Ergebnis:");

        jButtonStarten1.setText("Überprüfung starten");
        jButtonStarten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStarten1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonStarten1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAusgabe1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelWort)
                                .addComponent(TextFeld1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EingabeB, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(WahlTuringB)
                            .addGap(77, 77, 77)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTuring)
                                .addComponent(jTextFieldTuring, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WahlTuringB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTuring)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTuring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelWort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFeld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EingabeB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAusgabe1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonStarten1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EingabeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EingabeBActionPerformed

        wort = TextFeld1.getText();
    }//GEN-LAST:event_EingabeBActionPerformed

   
//   }
//     else if(/*Rückgabewert von überprüfung false*/){
//            ausgabe="Das Wort "+wort+" gehört nicht zur formalen Sprache. \nÜberprüfung nicht erfolgreich!";
//     }
//        else{
//            ausgabe="Das Wort "+wort+" gehört zur formalen Sprache. \nÜberprüfung erfolgreich!";
//        }
   
    private void WahlTuringBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WahlTuringBActionPerformed

         
         int rueckgabeWert = jFileChooser1.showOpenDialog(null);
         
         if(rueckgabeWert == jFileChooser1.APPROVE_OPTION)
         {
         dateiPfad = jFileChooser1.getSelectedFile().getAbsolutePath();
        jTextFieldTuring.setText(jFileChooser1.getSelectedFile().getName()) ;
         }
    }//GEN-LAST:event_WahlTuringBActionPerformed

    private void jTextFieldTuringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTuringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTuringActionPerformed

    private void jButtonStarten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStarten1ActionPerformed
      if(dateiPfad==null) {
        ausgabe="Keine Turingmaschine ausgewählt. \nÜberprüfung nicht möglich!"; 
        jTextAreaAusgabe1.setText(ausgabe);
        return;
      }
      else if(wort==null){
         ausgabe="Kein Wort eingegeben. \nÜberprüfung nicht möglich!";
         jTextAreaAusgabe1.setText(ausgabe);
         return;
      }
      textgruppe.Texteinlesen e = new textgruppe.Texteinlesen();
        try {
            e.dateiEinlesen(dateiPfad);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        e.angabenInArraySpeichern();
        turingband.Turingband t = new turingband.Turingband(wort);
        
        if(!e.wortUeberpruefen(wort)){
            ausgabe="Das Wort "+wort+" gehört nicht zum Eingabealphabet. \nÜberprüfung nicht erfolgreich!";
            jTextAreaAusgabe1.setText(ausgabe);
            return;
        }
        uebergangsfunktion.uebergangsfunktion u = new uebergangsfunktion.uebergangsfunktion();
        if(u.uebergang(/*Hashmap fehlt*/)){
            ausgabe="Das Wort "+wort+" gehört zur formalen Sprache. \nÜberprüfung erfolgreich!";
            jTextAreaAusgabe1.setText(ausgabe);
        }
        else{
        ausgabe="Das Wort "+wort+" gehört nicht zur formalen Sprache. \nÜberprüfung nicht erfolgreich!";;
        jTextAreaAusgabe1.setText(ausgabe);
        }
    }//GEN-LAST:event_jButtonStarten1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame n = new NewJFrame();
                n.setVisible(true);
        }
    
            });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EingabeB;
    private javax.swing.JTextField TextFeld1;
    private javax.swing.JButton WahlTuringB;
    public javax.swing.JButton jButtonStarten1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrameFileChooser;
    private javax.swing.JLabel jLabelAusgabe1;
    private javax.swing.JLabel jLabelTuring;
    private javax.swing.JLabel jLabelWort;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextAreaAusgabe1;
    private javax.swing.JTextField jTextFieldTuring;
    // End of variables declaration//GEN-END:variables
   //Eigene Variablen:
   public String wort;
   public String dateiPfad;
   public String ausgabe;

}     
